name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Setting up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Installing and building the project
        run: |
          npm install
          npm run build
      - name: Testing the project
        run: |
          npm test
